FROM public.ecr.aws/lambda/python:3.9

COPY pyproject.toml  .
RUN  pip3 install .[extract] --target "${LAMBDA_TASK_ROOT}"

COPY ./src/extract.py ${LAMBDA_TASK_ROOT}/
COPY ./src/common/*.py ${LAMBDA_TASK_ROOT}/common/

CMD [ "extract.lambda_handler" ]
