FROM public.ecr.aws/lambda/python:3.9

COPY pyproject.toml  .
RUN  pip3 install . --target "${LAMBDA_TASK_ROOT}"

COPY ./src/load.py ${LAMBDA_TASK_ROOT}/
COPY ./src/common/*.py ${LAMBDA_TASK_ROOT}/common/

CMD [ "load.lambda_handler" ]
